### ISSUE TITLE
Missing evidence field in admin interface

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#59]
In admin interface, the View and Edit Evidence views only show (and allow editing) of a subset of evidence item fields. They should all appear and be editable.

**Comment by malachig** [comment]
Some of this may have been addressed here: https://github.com/genome/civic-server/issues/56

**Comment by obigriffith** [comment]
Yes. perhaps some. But, it in a current pull I still don't see some evidence fields (variant origin, disease name, DOID, pubmed id, drug names)

**Comment by malachig** [comment]
Yeah, I see.  When I was going through I was more focused on the table (where we don't have room to view everything).  But yeah, when you go to actually edit an entity I guess it makes sense that you be able to edit everything.

**Comment by obigriffith** [comment]
Yeah. I agree that the main table should contain just a subset to make browsing convenient. But, when you click on details or want to edit you should have the complete set.

**Comment by acoffman** [comment]
Fixed in master!
