### ISSUE TITLE
500 error on add evidence

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#90]
Just tried submitting an evidence statement on public site got server error 500. :-(

![screen shot 2015-09-09 at 10 44 35 pm](https://cloud.githubusercontent.com/assets/1638042/9779744/bd3f12dc-5744-11e5-8fe1-943409ae5c7a.png)

**Comment by acoffman** [comment]
Looks like the form auto-completion help was sending back some unexpected parameters - I pushed out a hotfix to handle them for now (and tried submitting this evidence item as a test) and it seems to be working as expected. When Josh is back I will talk to him about a more permanent fix!

**Comment by obigriffith** [comment]
I guess this error is back. Trying to get this new piece of evidence out.
![screen shot 2015-09-24 at 8 33 32 pm](https://cloud.githubusercontent.com/assets/1638042/10091066/3ef1500c-62fc-11e5-9361-8725c219344c.png)

**Comment by obigriffith** [comment]
This seems to have been fixed. The above evidence statement was successfully submitted, approved and is now live!
